name: feature request
description: suggest an idea or a new site to support
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: the idea
      description: what would you like nymric to do
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: why
      description: what problem does it solve
    validations:
      required: false
